### ISSUE TITLE
report.CRITICAL: Unable to unserialize value, string is corrupted.

### ISSUE THREAD

**Issue by jobrandon** [thaiphan/magento2-s3#50] opened 2018-06-26 03:19 UTC
Hi,

I execute the bin/magento s3:storage:export 
and got this error.
 {"exception":"[object] (InvalidArgumentException(code: 0): Unable to unserialize value, string is corrupted. at /var/www/html/stg/vendor/magento/framework/Serialize/Serializer/Serialize.php:38)"} []

**Comment by thaiphan** [comment] 2018-06-28 07:06
Hi @jobrandon,
This might have been caused by an old bug that should be addressed by the latest version. Can you confirm what version you're using?
Regards,
Thai

**Comment by jobrandon** [comment] 2018-06-28 07:07
Magento version 2.2.3. I found out that the problem is a unserializing the custom headers.

**Comment by thaiphan** [comment] 2018-06-28 07:08
Have you resolved the problem or do you still need assistance?

**Comment by jobrandon** [comment] 2018-06-28 07:10
My solution was a quick fix. And I remove the custom header which actually not necessary for my use.

**Comment by jobrandon** [comment] 2018-06-28 07:15
Then I got this message. Is this related to the fix?

`<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>2EC08E0523DBAF47</RequestId><HostId>a/MrVnQgp2Yhm1jrl9AbXtcigMGSK8lbfswr4wEGQxln/G7Pb+lWrAbzLbGPGLrmu4Elvs3maZ0=</HostId></Error> at /var/www/html/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:191, GuzzleHttp\\Exception\\ClientException(code: 403): Client error: `PUT https://s3.ap-southeast-1.amazonaws.com/images-app.testing.com/assets/external/images/icons/icons_48-browsing-white.png` resulted in a `403 Forbidden` response:
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>2EC08E (truncated...)
 at /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)"} []
[2018-06-28 06:41:18] report.CRITICAL: Error executing "PutObject" on "https://s3.ap-southeast-1.amazonaws.com/images-app.testing.com/assets/external/images/icons/icons_48-browsing-white.png"; AWS HTTP error: Client error: `PUT https://s3.ap-southeast-1.amazonaws.com/images-app.testing.com/assets/external/images/icons/icons_48-browsing-white.png` resulted in a `403 Forbidden` response:`

**Comment by thaiphan** [comment] 2018-06-28 12:11
That reads like your S3 credentials are incorrect. Can you review `s3:config:list` and see if everything is correct?

**Comment by jobrandon** [comment] 2018-06-28 12:12
Thanks!, it works fine now. The only thing now is the custom header whenever necessary to use it.

**Comment by cybpoonam** [comment] 2018-08-12 14:56
Hi @jobrandon,

how you resoled this issue. i am also getting same issue.

report.CRITICAL: Unable to unserialize value, string is corrupted. {"exception":"[object] (InvalidArgumentException(code: 0): Unable to unserialize value, string is corrupted. at /spdata/specapps/vansdev4/vendor/magento/framework/Serialize/Serializer/Serialize.php:38)"} []

Thanks
Poonam

**Comment by cybpoonam** [comment] 2018-08-12 14:57
Hi @thaiphan ,

Can you please suggest, how i can fix this issue.

Thanks

**Comment by vijaydcyb** [comment] 2018-08-17 07:19
Hi @jobrandom

Could you please let us know how you resolved that access denied issue 

I have set $meta['ACL' =>'public-write']; in s3.php
But still issue persist

@thai you please also suggest the solution 

Thanks

**Comment by vijaydcyb** [comment] 2018-08-17 08:05
Hi @jobrandon

Hi already tried this. Commented the code but while adding images from admin it throws the access denied error

The credentials are correct ones

**Comment by thaiphan** [comment] 2018-10-25 02:49
I'm closing this ticket. If problems persist, feel free to reply here or open a new ticket!

**Closed by thaiphan** 2018-10-25 02:49 UTC
Labels: bug
